### 00. PyTorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#### Introduction to Tensors

##### Creating Tensors

PyTorch Tensors documentation ``https://docs.pytorch.org/docs/stable/tensors.html``

In [3]:
# scalar torch.tensor
scalar = torch.tensor(7)
print("scalar torch.tensor:", scalar)

# numbes of dimensions of the scalar
print("scalar dimensions:", scalar.ndim)

# get scalar value back as Python integer
print("scalar value as Python integer:", scalar.item())

scalar torch.tensor: tensor(7)
scalar dimensions: 0
scalar value as Python integer: 7


In [4]:
# vector torch.tensor
vector = torch.tensor([7, 7])
print("vector torch.tensor:", vector)

# numbes of dimensions of the vector
print("vector dimensions:", vector.ndim)

# get vector shape
print("vector shape:", vector.shape)

vector torch.tensor: tensor([7, 7])
vector dimensions: 1
vector shape: torch.Size([2])


In [5]:
# MATRIX torch.tensor
MATRIX = torch.tensor([[7,8 ], [9, 10]])
print("MATRIX torch.tensor:")
print(MATRIX)

# numbes of dimensions of the MATRIX
print("MATRIX dimensions:", MATRIX.ndim)

# get MATRIX shape
print("MATRIX shape:", MATRIX.shape)

MATRIX torch.tensor:
tensor([[ 7,  8],
        [ 9, 10]])
MATRIX dimensions: 2
MATRIX shape: torch.Size([2, 2])


In [6]:
# TENSOR torch.tensor
TENSOR = torch.tensor([[[1, 2, 3],
						[4, 5, 6],
						[7, 8, 9]]])
print("TENSOR torch.tensor:")
print(TENSOR)

# numbes of dimensions of the TENSOR
print("TENSOR dimensions:", TENSOR.ndim)

# get TENSOR shape
print("TENSOR shape:", TENSOR.shape)

TENSOR torch.tensor:
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
TENSOR dimensions: 3
TENSOR shape: torch.Size([1, 3, 3])


##### Random Tensors

PyTorch random Tensors documentation ``https://docs.pytorch.org/docs/stable/generated/torch.rand.html``

In [11]:
# create a random torch.tensor of shape (3, 4)
random_tensor = torch.rand(size=(3, 4))
print("random torch.tensor:")
print(random_tensor)

# numbes of dimensions of the random_tensor
print("random_tensor dimensions:", random_tensor.ndim)

# get random_tensor shape
print("random_tensor shape:", random_tensor.shape)

random torch.tensor:
tensor([[0.7753, 0.6050, 0.2227, 0.5376],
        [0.6754, 0.9862, 0.5066, 0.1368],
        [0.7421, 0.9002, 0.6840, 0.5586]])
random_tensor dimensions: 2
random_tensor shape: torch.Size([3, 4])


In [14]:
# create a random torch.tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))

# numbes of dimensions of the random_tensor
print("random_image_size_tensor dimensions:", random_image_size_tensor.ndim)

# get random_tensor shape
print("random_image_size_tensor shape:", random_image_size_tensor.shape)

random_image_size_tensor dimensions: 3
random_image_size_tensor shape: torch.Size([224, 224, 3])


##### Zeros and Ones Tensors

In [ ]:
# create a torch.tensor full of zeros
zeros = torch.zeros(size=(3, 4))
print("zeros torch.tensor:")
print(zeros)

zeros torch.tensor:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [16]:
# create a torch.tensor full of ones
ones = torch.ones(size=(3, 4))
print("ones torch.tensor:")
print(ones)

ones torch.tensor:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
